apiVersion: v1
kind: Service
metadata:
  name: net-certmanager-webhook
  labels:
    {{- include "net-certmanager.labels" . | nindent 4 }}
    {{- include "net-certmanager.webhookSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  selector:
    {{- include "net-certmanager.selectorLabels" . | nindent 4 }}
    {{- include "net-certmanager.webhookSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.service.ports | toYaml | nindent 2 }}
