apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: knative-internal-encryption-issuer
  labels:
    {{- include "net-certmanager.labels" . | nindent 4 }}
spec:
  ca:
    secretName: knative-internal-encryption-ca
